version: '3.8'

services:
  # PHP-FPM контейнер
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: wbd_php
    volumes:
      - ./src:/var/www/html
    networks:
      - wbd_network
    depends_on:
      - mariadb
      - redis

  # Nginx контейнер
  nginx:
    image: nginx:latest
    container_name: wbd_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wbd_network
    depends_on:
      - php

  # MariaDB контейнер
  mariadb:
    image: mariadb:10.11
    container_name: wbd_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wbd_network

  # Redis контейнер
  redis:
    image: redis:latest
    container_name: wbd_redis
    ports:
      - "6379:6379"
    networks:
      - wbd_network

volumes:
  mariadb_data:

networks:
  wbd_network:
    driver: bridge
